// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ToastController from "./toast_controller"
import ModalController from "./modal_controller"
import DropdownController from "./dropdown_controller"
import FilterController from "./filter_controller"
import StatusController from "./status_controller"
import DropdownEditController from "./dropdown_edit_controller"
import TextEditController from "./text_edit_controller"

application.register("hello", HelloController)
application.register("toast", ToastController)
application.register("modal", ModalController)
application.register("dropdown", DropdownController)
application.register("filter", FilterController)
application.register("status", StatusController)
application.register("dropdown-edit", DropdownEditController)
application.register("text-edit", TextEditController)
