// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DropdownEditController from "./dropdown_edit_controller"
application.register("dropdown-edit", DropdownEditController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ModalNotesController from "./modal_notes_controller"
application.register("modal-notes", ModalNotesController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import StatusController from "./status_controller"
application.register("status", StatusController)

import SummarizeController from "./summarize_controller"
application.register("summarize", SummarizeController)

import TextEditController from "./text_edit_controller"
application.register("text-edit", TextEditController)

import ToHtmlController from "./to_html_controller"
application.register("to-html", ToHtmlController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
