# Basic settings
verify_signatures: false
concurrency: 1

PreCommit:
  StandardRbAutocorrect:
    enabled: true
    command: ['bundle', 'exec', 'standardrb']
    flags: ['--fix', '--except', 'Style/GlobalVars']
    on_warn: pass

  RSpec:
    enabled: false
    command: ['bundle', 'exec', 'rspec']
    on_warn: fail

  # JavaScript
  EsLint:
    enabled: false
    required_executable: './node_modules/.bin/eslint'
    include:
      - '**/*.js'
      - '**/*.ts'

  # Rails Security
  BundleAudit:
    enabled: true
    command: ['bundle', 'exec', 'bundle-audit']

  Brakeman:
    enabled: true
    command: ['bundle', 'exec', 'brakeman']
    flags: ['-q', '--no-summary']

CommitMsg:
  CapitalizedSubject:
    enabled: false

PrePush:
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec']
    on_warn: fail

  CustomSnykCheck:
    enabled: false
    required: true
    description: 'Running Snyk security checks'
    command: ['bash', '-c']
    flags: ['
      exit_code=0;
      echo "🔍 Running Snyk security checks...";
      snyk test --file=Gemfile.lock --fail-on=upgradable || exit_code=1;
      snyk code test || exit_code=1;
      if [ "$exit_code" -ne 0 ]; then
        echo "❌ Commit blocked due to security issues";
        echo "Run snyk test or snyk code test manually to see detailed reports";
        exit 1;
      fi;
      echo "✅ Snyk security checks passed";
      exit 0']

  PythonLinting:
    enabled: true
    command: ['docker run --rm -t asap_pdf:ci ./run_linting.sh **/*.py']
    include:
      - 'python_components/**/*.py'

PostCheckout:
  ALL:
    quiet: true
  IndexTags:
    enabled: true
