name: Python Component Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  LINTING_BUDGET: 3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./python_components/requirements.txt ]; then pip install -r ./python_components/requirements.txt; fi
    - name: Run Linting
      run: |
        ./python_components/scripts/ci_run_linting.sh ./python_components/**/**.py